apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: greeter-weather-requester
  namespace: default
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    constraints:
    - key: "destination.labels[app]"
      values: ["weather-proxy"]

---

apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: greeter-weather-requester-binding
  namespace: default 
spec:
  subjects:
  - properties:
      source.namespace: "istio-system"
  - properties:
      source.namespace: "default"
  - properties:
      source.namespace: "greet-ns"
  roleRef:
    kind: ServiceRole
    name: "greeter-weather-requester"
