apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: greetandweather-service
spec:
    host: greetandweather-service
    subsets:
    - name: v1 
      labels:
        version: v1